/* defines.h
 * Purpose: Has all of the pin number assignments for the motors. Holds constants
 * for the frame class and spi class.
 */

#ifndef _DEFINES
#define _DEFINES

/* STATE MACHINE TYPES */

typedef enum {
    P1,
    P2,
    P3,
    P4,
    MOVING
} STATE_TYPE;

typedef enum {
    MOVE_TO_P1,
    MOVE_TO_P2,
    MOVE_TO_P3,
    MOVE_TO_P4,
    IDLE
} MOVE_COMMAND;

/* DECLARED SO THAT ODD MESSAGES GO TO ESP1, AND EVEN MESSAGES GO TO ESP2 */
typedef enum {
    END_STAGE,
    WHEELS_UP = 1,
    WHEELS_DOWN = 3,
    MOVE_FORWARDS_24_IN = 5,
    MOVE_BACKWARDS_24_IN = 7,
    INITIATE_TURN_MOTORS = 2,
    RETURN_TURN_MOTORS = 4,
    TURN_RIGHT_90_DEGREES = 9,
    TURN_LEFT_90_DEGREES = 11,
    TURN_RIGHT_45_DEGREES = 13,
    TURN_LEFT_45_DEGREES = 15,
    TURN_RIGHT_135_DEGREES = 17,
    TURN_LEFT_135_DEGREES = 19,
    FINISH_MOVEMENT
} MOTOR_COMMAND;

/* ESP1 PINOUT */

#define DRIVE_ENABLE 13

#define FRONT_DRIVE_DIRECTION 12
#define FRONT_DRIVE_PULSE 14

#define BACK_DRIVE_DIRECTION 27
#define BACK_DRIVE_PULSE 26

#define LIFT_ENABLE 18 /* CHANGED */
#define LIFT_DIRECTION 23

#define LIFT1_PULSE 19 /* CHANGED */
#define LIFT2_PULSE 21 /* CHANGED */
#define LIFT3_PULSE 2 /* CHANGED */
#define LIFT4_PULSE 15 /* CHANGED */

/* ESP2 PINOUT */

#define TURN_ENABLE 13

#define TURN1_PULSE 14 /* CHANGED */
#define TURN1_DIRECTION 12 /* CHANGED */

#define TURN2_PULSE 33 /* CHANGED */
#define TURN2_DIRECTION 25 /* CHANGED */

#define TURN3_PULSE 32 /* CHANGED */
#define TURN3_DIRECTION 23

#define TURN4_PULSE 26 /* CHANGED */
#define TURN4_DIRECTION 27 /* CHANGED */

/* SPI Pin Defines. Not used anymore */
#define SPI_CLK 18
#define VSPI_CIPO 19 // controller in peripheral out
#define VSPI_COPI 23 // controller out peripheral in
#define VSPI_CS 5 

/* UART Pin Defines. RXD2 and TXD2 are the specified pins on the board, while
RXD1 and TXD1 are both remapped for UART channel 1 */
#define TXD1 5
#define RXD1 18
#define TXD2 17
#define RXD2 16

/* DEFINES FOR CONVERTING REAL LIFE DISTANCES TO STEPS FOR THE MOTORS */
#define WHEEL_DIAMETER 5.9035
#define WHEEL_CIRCUMFERENCE (PI * WHEEL_DIAMETER)
#define DRIVE_GEARBOX_RATIO 30
#define TURN_GEARBOX_RATIO 100
#define MICROSTEP 8
#define FULL_DRIVE_ROTATION (MICROSTEP * 200 * DRIVE_GEARBOX_RATIO)
#define FULL_TURN_ROTATION (MICROSTEP * 200 * TURN_GEARBOX_RATIO)
#define STEPS_PER_LIFT_HUNDREDTH_INCH 28846 /* NOTE: EXPERIMENTALLY FOUND */

/* THESE ARE THE ONLY AMOUNTS THE TURN MOTORS WILL EVER NEED TO TURN */
#define TURN_1_3_NUM_STEPS ((45.0f / 360.0f) * (float)FULL_TURN_ROTATION) // 40,000
#define TURN_2_4_NUM_STEPS ((135.0f / 360.0f) * (float)FULL_TURN_ROTATION) // 120,000

/* SPEED AND ACCELERATION DEFINES FOR ALL MOTOR TYPES. NOTE: INCREASING THESE
VALUES MAY CAUSE MOTORS TO STALL */
#define TURN_2_4_MAX_SPEED 22500
#define TURN_1_3_MAX_SPEED (TURN_2_4_MAX_SPEED / 3)

#define TURN_2_4_ACCEL 22500
#define TURN_1_3_ACCEL (TURN_2_4_ACCEL / 3)

#define DRIVE_MAX_SPEED 15000
#define DRIVE_ACCEL 10000

#define LIFT_MAX_SPEED 30000 
#define LIFT_ACCEL 1500

#endif